### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by EugeneTerentev98** [Kellermaenn/masscan-web-ui#1]
Hi! 
I finished setting up web server and database for masscan. But when i try to access web page i'm getting an error:

Fatal error: Uncaught TypeError: PDOStatement::fetch(): Argument #1 ($mode) must be of type int, string given in /var/www/html/includes/functions.php:16 Stack trace: #0 /var/www/html/includes/functions.php(16): PDOStatement->fetch() #1 /var/www/html/includes/functions.php(39): getPdo() #2 /var/www/html/includes/data_validation.php(43): browse() #3 /var/www/html/index.php(5): require('...') #4 {main} thrown in /var/www/html/includes/functions.php on line 16

Can you help my diagnose where the problem is?

Whe only thing different from the instructions, is that my web server listening on different port, rather than 80

**Comment by EugeneTerentev98** [comment]
Found the issue and a fix here 
https://github.com/offensive-security/masscan-web-ui/issues/22
